In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
lst = [[1,2,3],
       [1,2,3],
       [1,2,3]]
       

In [3]:
type(lst)

list

In [4]:
arr = np.array(lst)

In [5]:
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.ndim

2

In [8]:
arr.shape

(3, 3)

In [9]:
arr.size

9

In [10]:
arr.dtype

dtype('int64')

In [11]:
zeros = np.zeros((5,3))

In [12]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
ones = np.ones((6,3))

In [14]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])