In [ ]:
import numpy as np

In [2]:
np.random.random((3,3))

array([[0.74765241, 0.05562228, 0.20943296],
       [0.94191633, 0.14980621, 0.08354789],
       [0.54990749, 0.96571213, 0.52025704]])

In [3]:
arr = np.random.random((3,3))

In [6]:
np.arange(1,10,3)

array([1, 4, 7])

In [7]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [8]:
arr = np.random.random((4,3))

In [9]:
arr

array([[0.89153384, 0.94672854, 0.06292848],
       [0.41611834, 0.17627764, 0.00665459],
       [0.69017264, 0.10564531, 0.86333714],
       [0.0609101 , 0.18393503, 0.99732811]])

In [10]:
arr = np.reshape(arr , (3,4))

In [11]:
arr

array([[0.89153384, 0.94672854, 0.06292848, 0.41611834],
       [0.17627764, 0.00665459, 0.69017264, 0.10564531],
       [0.86333714, 0.0609101 , 0.18393503, 0.99732811]])

In [12]:
arr = np.reshape(arr , (6,2))

In [13]:
arr

array([[0.89153384, 0.94672854],
       [0.06292848, 0.41611834],
       [0.17627764, 0.00665459],
       [0.69017264, 0.10564531],
       [0.86333714, 0.0609101 ],
       [0.18393503, 0.99732811]])

In [ ]:
arr.flatten()