In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

arr2 = np.array([[9,8,7],
               [6,5,4],
               [3,2,1]])

arr3 = np.array([[9,8,7,5],
               [6,5,4,2],
               [3,2,1,5]])

In [3]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [5]:
arr1 + arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [6]:
arr2 * arr1

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [7]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [9]:
(1*9) + (2*6) + (3*3)

30

In [10]:
arr1.dot(arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [11]:
arr2.dot(arr1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [ ]:
 arr1

In [12]:
arr = np.array([1,2,3,4,5])

In [13]:
arr[:-2]

array([1, 2, 3])

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr1[ 1: , 1 : ]

array([[5, 6],
       [8, 9]])